generatorOptions:
  disableNameSuffixHash: true
images:
- name: python-tools
  newName: lthub-registry.cn-beijing.cr.aliyuncs.com/library/tools
  newTag: python-v0.1.3
patches:
- path: patchs/affinity-tolerations.yaml
  target:
    kind: Deployment
- path: patchs/affinity-tolerations.yaml
  target:
    kind: StatefulSet
patchesStrategicMerge:
- patchs/mysql.yaml
- patchs/vmstorage.yaml
- patchs/vmselect.yaml
- patchs/vminsert.yaml
resources:
- ../../base
- svc-outside
- nginx.yaml
- pvc.yaml
# 用于自动创建项目 绑定项目负责人 注意调整yaml中的环境变量
# - action/create-project.yaml