apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: redis:6.2
          name: redis
          ports:
            - containerPort: 6379
              name: mysql
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''