---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: alert-send-by-aggr
spec:
  schedule: 0 * * * *
  concurrencyPolicy: Allow
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: 9999
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: host-time
              hostPath:
                path: /etc/localtime
                type: ''
            - name: public-script
              configMap:
                name: public-script
            - name: public-script-base
              configMap:
                name: public-script-base
          containers:
            - name: alert-send-by-aggr
              image: python-tools
              command:
                - python3
              args:
                - /app/src/alert-send-by-aggr.py
              volumeMounts:
                - name: host-time
                  mountPath: /etc/localtime
                  readOnly: true
                - name: public-script-base
                  mountPath: /app/src/base
                - name: public-script
                  mountPath: /app/src/alert-send-by-aggr.py
                  subPath: alert-send-by-aggr.py
          imagePullSecrets:
            - name: lthub