---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vminsert
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: vminsert
          command:
            - ./vminsert-prod
          args:
            - '-storageNode=vmstorage-0.vmstorage-server:8400,vmstorage-1.vmstorage-server:8400,vmstorage-2.vmstorage-server:8400,vmstorage-3.vmstorage-server:8400,vmstorage-4.vmstorage-server:8400'
          resources:
            limits:
              cpu: 8000m
              memory: 30720Mi
            requests:
              cpu: 50m
              memory: 50Mi