---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: vmselect
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: vmselect
          command:
            - ./vmselect-prod
          args:
            - '-selectNode=vmselect-0.vmselect-server:8481,vmselect-1.vmselect-server:8481,vmselect-2.vmselect-server:8481,vmselect-3.vmselect-server:8481,vmselect-4.vmselect-server:8481'
            - '-storageNode=vmstorage-0.vmstorage-server:8401,vmstorage-1.vmstorage-server:8401,vmstorage-2.vmstorage-server:8401,vmstorage-3.vmstorage-server:8401,vmstorage-4.vmstorage-server:8401'
            - '-cacheDataPath=./vmselect-cache'
          resources:
            limits:
              cpu: 8000m
              memory: 30720Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: vmdata
              mountPath: /vmselect-cache
  volumeClaimTemplates:
    - metadata:
        name: vmdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "monitor-disk"
        resources:
          requests:
            storage: 20Gi